### ISSUE TITLE
Issue with Meteor.call()/Meteor methods after page reload

### ISSUE THREAD

**Issue by ZJoveski** [TurkServer/turkserver-meteor#52]
I was wondering if you have ever experienced an issue like the following. 

When people accept our experiment HIT, we initially keep them in the lobby and we set their lobby status to "not ready". Before their status is changed to "ready" they have to go through a couple of pages (one with a short outline of the HIT, and another one with full description of the game). They navigate from one page to the next by simply clicking a button. When the corresponding button is clicked, we invoke a Meteor method on the server side (using Meteor.call()) which updates the document of that user in a collection which keeps track of the user's progress before their lobby status is changed to ready, and this document is used to render the appropriate template on the client side (much like the "Recruiting" collection is used in the Prisoner's Dilemma app of @ldworkin).

Everything seems fine if people do not reload their page - they easily navigate through all these pages. However, if, for some reason, they reload their page, the Meteor.call() statement invoked upon a button click, does not start the execution of the corresponding server-side Meteor method (though, the click event itself is registered on the client side). The funny thing is that upon restarting the server (which I do by simply re-deploying the app on Modulus), all calls to Meteor methods are processed (multiple clicks before the restart result in equally many executions of the corresponding Meteor method). It is as if they are postponed until the client-server connection is "properly" re-established with the server restart.

Do you have any ideas on where the problem may lie? 

Any help would be very much appreciated!

**Comment by mizzao** [comment]
I think this may be caused by one of the following:

- #44: a temporary bug which I will fix soon. You can see if this is the problem by forcing `mizzao:partitioner@0.5.6` and seeing if the issue goes away.
- #37: sometimes multitasking users will open multiple tabs by accident and this can break the login tracking. I know what is causing this but haven't got around to fixing it yet. You can help with that!

Have you been able to reproduce the state on a client which makes the methods non-responsive? I think that is the first step, and if you can do so then we are 90% of the way to a fix.

**Comment by mizzao** [comment]
@ZJoveski: have you managed to track down anything more about this?

**Comment by ZJoveski** [comment]
No, unfortunately. I am pretty sure the issue is not <code>izzao:partitioner@0.5.6</code>, as I am still using the pre-Meteor 1.2 TurkServer version and <code>izzao:partitioner@0.5.6</code> does appear in the "versions" file. The issue is definitely not limited  to multitasking users. 

I have been able to reproduce the problem using my worker account on the MTurk sandbox - it really only takes one reloading of the screen and the issue appears. 

I have been trying hard to isolate the problem by stripping our application of as much of the code as possible. My best guess is that it has to do something with the publications on the server-side as removing the file containing the publications of collections with experiment-related data, eliminates the problem with button-reponsiveness on the screens prior to the actual experiment. I have tried removing the publications from the file one-by-one, but that's where I get lost, because I could not identify which collection (or a group of collections) is causing the problem. 

Perhaps the problem is with the number of publications I have...

I will try to create a repository with the simplest version of the code with which I am able to reproduce the error by the end of today, so that if you have a chance, you could have a look at it.

In the meantime, we tried running some tests where we ask people to not reload their screens and potentially exclude those who gave this issue due to external connection loss from the actual experiment, but we found out that the problem is not limited to just the navigation in the pre-experiment phase - it also appeared in the actual experiment (people we not able to change colors), and it would likely become unmanageabla in this way for significantly larger experiments.

**Comment by mizzao** [comment]
Is your repo public? If so, could you just point me to the code and I can see if anything is strange?

And just to be clear, this issue still happens if the user only has one tab open and they just reload it?

**Comment by ZJoveski** [comment]
Yes, the repo is public. Here is the file containing the publications

https://github.com/ZJoveski/DC/blob/master/server/app/publications.js

Alse, here is where I am doing the partitioning of the collections

https://github.com/ZJoveski/DC/blob/master/lib/models/app/app_models.js


And yes, this issue still happens if the user only has one tab open and they just reload it (or there is a temporary loss of connection).

**Comment by ZJoveski** [comment]
I think the following issue may be related to the above one. Sometimes, if I log out from the TurkServer admin account and try to log in again, nothing happens (I do not get to the TurkServer Overview page). But if I restart the app from the server while I am at the login screen, the login request ( Meteor.loginWithPassword) gets processed when the app restarts and I get to the TurkServer Overview page.

**Comment by mizzao** [comment]
I think your publications and collections generally look fine - except maybe the messages publication; if you are trying to do some sort of [reactive join](https://www.discovermeteor.com/blog/reactive-joins-in-meteor/), that is not the way to do it. Only the cursor you send will get updated and you will have to make sure to re-subscribe to this whenever the experiment, neighborhood, etc. changes. 

With regard to the login problem, do you mean that if you log out and enter the password to log in, nothing happens? That's strange, it sounds like there is some protocol error that is causing the clients to lose connection to the server.

With regard to reproducing the error, is that only when you are running in the sandbox, or can you also reproduce it running locally without the sandbox? If it's only in the sandbox that sounds similar to #37.

Finally, if you experience unresponsiveness of buttons on the client side, that suggests you might be accidentally publishing much more data than you intend to on the client. Maybe you can install something like [mongol](https://github.com/msavin/Mongol) and see how big your client-side collections are getting.

**Comment by ZJoveski** [comment]
I apologize for the extremely late response. We did try going with a new version of our app, without TurkServer, and that seemed to fix the issues. We were able to successfully run two short test sessions and one full experiment session.

Regarding the messages publication, that was something that I actually found online. It may not be the the best way to go, and we may change it, but it seemed to do the job with the new version of our app that does not use TurkServer. Do you think it could somehow interfere with the normal functioning of TurkServer?

As for the login problem, yes it was happening very often - if I log out and enter the password to log in, nothing happens, but after I restart the server, the log in request gets processed and I can see the admin screen. 

I have not tried reproducing the error locally yet, but I do not think the problem is with the opening of multiple tabs, as I was able to reproduce it on the sandbox with only a single tab being opened. I will try that, as well as looking at the sizes of the client-side collections. But in the next couple of weeks we will probably use the new version of the app because we really need to run a few more experiment sessions and gather data for analysis (though I really miss the convenience of TurkServer in setting up the HIT and processing the assignments and payments).

**Comment by mizzao** [comment]
Hi @ZJoveski, sorry to hear that TurkServer didn't work out for you, and also that you are probably re-implementing a lot of the TurkServer functions from scratch on your own version. This is the type of thing I hoped to avoid, but I guess we're not quite there yet.

I was hoping that if you encountered any issues of this sort you'd be able to help fix them, but at the very least you can perhaps let me know any interesting ideas you get in building your experiment that we can keep in mind for future updates.

**Comment by mizzao** [comment]
Any chance you are using Mongol in your development process? It's possible it may interfere with partitioner.

**Comment by ZJoveski** [comment]
No, I have not used Mongol at all.
