### ISSUE TITLE
Incredibly slow build times using Turkserver with Meteor 1.2

### ISSUE THREAD

**Issue by ejolly** [TurkServer/turkserver-meteor#54]
I've seen that some people have generally experienced issues with [slower build times for apps after upgrading to Meteor 1.2](https://github.com/meteor/meteor/issues/5269/), but any app I have that includes Turkserver is *incredibly* slow to build in comparison to apps that don't include Turkserver with the latest version of both Meteor and Turkserver. Are there any suggestions for dealing with this (e.g. package add options, removing irrelevant packages), or do we simply have to wait until the build speed issues are taken care of on the Meteor side of things?

**Comment by mizzao** [comment]
I was thinking about transitioning the MTurk API to use https://github.com/JoseBarrios/mturk-api, which would get rid of a lot of the outdated binary dependencies completely, but haven't gotten around to that yet.

Happy to take any contributions or ideas you may have, though.

**Comment by mizzao** [comment]
How slow is your build exactly?

**Comment by ejolly** [comment]
I updated to 1.2.1 about a week ago and didn't measure build times with the 1.2.0 release. Currently it's a tiny bit faster with that update, but I'm averaging about 1 minute 15 seconds. In versions < 1.2, the build time was never more than 30 seconds.

**Comment by mizzao** [comment]
Hey @ejolly, I started a new branch using https://github.com/JoseBarrios/mturk-api: https://github.com/HarvardEconCS/turkserver-meteor/tree/new-api

I think the build process here should be much faster, but the MTurk API looks a little different and hence some of the functions might be broken and need fixing. But if you find building to be faster, then we're on the right track.

**Comment by mizzao** [comment]
As mentioned at https://github.com/HarvardEconCS/turkserver-meteor/issues/24#issuecomment-164325115, things might be much faster for you after switching to the new underlying MTurk API. Let me know if the build is smoother.
