### ISSUE TITLE
Assignments can be completed that are no longer assigned on MTurk

### ISSUE THREAD

**Issue by mizzao** [TurkServer/turkserver-meteor#69]
Working with Nasrin and @kgao on this; causes assignments that can't be refreshed via the admin console

We should handle these gracefully when refreshing assignment statuses. If an assignment is marked as completed but doesn't actually exist, we should set it to returned and remove it from the list of assignments.

https://github.com/TurkServer/turkserver-meteor/blob/master/server/assignment.js

**Comment by kgao** [comment]
Fixed: https://github.com/TurkServer/turkserver-meteor/pull/75
