### ISSUE TITLE
Intermittent disconnections from the server

### ISSUE THREAD

**Issue by nasrinm** [TurkServer/turkserver-meteor#84]
I'm testing the master branch on sandbox, and getting the following error in the middle of the experiment. 

> You have been disconnected from the server. Please check your Internet connection.

There are only two users connected to the server, so it's not a server load issue. Moreoever, my server is up and running, so might be a connection issue from turkserver side.

**Comment by mizzao** [comment]
This is caused by the Meteor client being unable to communicate with the server. It could happen from any number of issues, but probably has to do with the code specific to your app (I've been using the latest branch of TurkServer in my apps without any problems.)

We'd need a bit more debugging to be able to reproduce and fix this.

**Comment by kgao** [comment]
Agree. 
It's hard to reproduce based on the discribtion. If there is any error throwing out in runtime, it could crash the meteor app and restart automatically from server, should retrieve the log to see what's the real issue.
Suggest to run debug:
http://stackoverflow.com/questions/11034941/meteor-debug-on-server-side

**Comment by nasrinm** [comment]
Thanks. I will run debug then and see what I get.

**Comment by mizzao** [comment]
I think one likely reason for this is that the publications were potentially set up incorrectly in your app, and as you collect more data it is somehow getting pushed to all clients and causing these lag issues and disconnections. This is a common mistake to make in Meteor apps.

You can use something like Mongol (https://github.com/msavin/Mongol) to check what data is getting pushed to your client. I wouldn’t do this in production; make a copy of your database locally and examine how much data is getting loaded in the client-side collections.

**Comment by nasrinm** [comment]
Confirming that pushing more data to the clients was triggering this problem on my end.
