### ISSUE TITLE
Stylus compiler error

### ISSUE THREAD

**Issue by antxa** [TurkServer/turkserver-meteor#94]
Hi,
I'm trying to follow the basic tutorial of TurkServer ([https://turkserver.readthedocs.io/en/latest/examples/tutorial.html]) but when I add the TurkServer package (`meteor add mizzao:turkserver`), I got this error:

```
Errors prevented startup:                  
   
   While processing files with stylus (for target web.browser):
   packages/mizzao:turkserver/client/ts_client.styl: Stylus compiler error:
   client/ts_client.styl:12:15
   8| .form-control.width-medium
   9|   width: 160px
   10| 
   11| .form-control.width-long
   12|   width: 240px
   ---------------------^
   13| 
   14| 
   
   fs.exists is not a function
```

I read on the web that it could be because of the version of stylus, and I changed its version number in .meteor/versions file as they suggested, but then I got another error.

Do you know why is it and how can I resolve it?

Thanks!

**Comment by mizzao** [comment]
Getting rid of stylus in #100 should fix this.
